version: "1.0"
services:
  mongo:
    container_name: mongoDB
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - database-network
    volumes:
      - mongo-data:/data/db

  app:
    container_name: app
    build: .
    environment:
      - MONGOURI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    networks:
      - database-network
    depends_on:
      - mongo
    volumes:
      - ./src:/usr/app/src

networks:
  database-network:
    driver: bridge

volumes:
  mongo-data: