version: "1.0"
services:
  mongo:
    container_name: mongoDB
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - mongo_network
    volumes:
      - mongo_data:/data/db
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - MONGOURI=${MONGOURI}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data:
