version: "1.0"
services:
  mongo:
    container_name: mongoDB
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=${BACKEND_PORT}
      - MONGOURI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    #    ports:
    #      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app-network
    depends_on:
      - mongo
    volumes:
      - ./backend/src:/usr/app/src

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PORT=${FRONTEND_PORT}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network
    volumes:
      - ./frontend/src:/usr/app/src

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: