version: "1.0"
services:
  mongo:
    container_name: mongoDB
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - database-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - MONGOURI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    restart: always
    networks:
      - database-network

networks:
  database-network:
    driver: bridge


volumes:
  mongo_data:
