services:
  - name: nest-backend
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    envVars:
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: PORT
        value: ${PORT}
      - key: MONGOURI
        value: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}
    autoDeploy: true

databases:
  - name: my-mongo-db
    type: mongodb
    plan: free
    region: oregon
    autoDeploy: true