version: "1.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - MONGOURI=mongodb+srv://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@<cluster-url>/${MONGO_INITDB_DATABASE}?retryWrites=true&w=majority

      - MONGOURI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data:
